### ISSUE TITLE
Feature - workflow for docker build and push to dockerhub

### ISSUE THREAD

**Issue by wim-de-groot** [rcomanne/docker-registry-gui-golang#2]
Seeing that the application will be build using the `Dockerfile` we only have to build and push the docker image to dockerhub. I already provided a [pull-request](https://github.com/rcomanne/docker-registry-gui-golang/pull/1). Also I was able to test the workflow to some extend using [act](https://github.com/nektos/act). The only problem is that in the final step a github token is needed and that is not available on forks. Would you be so kind @rcomanne to review this pull request and merge it into the existing repository when ready.

**Comment by rcomanne** [comment]
Merged and added secrets for connecting to the Docker API
